### ISSUE TITLE
Issue with libpoppler shared library

### ISSUE THREAD

**Issue by AA24KK** [otfried/ipe-tools#36]
Hello,

I have cloned the latest version (73f4cef) and tried to use pdftoipe, which fails giving the error

`pdftoipe: error while loading shared libraries: libpoppler.so.85: cannot open shared object file: No such file or directory`

On my system (arch linux) I have installed the latest version of the `poppler` package, which provides the file `libpoppler.so.86` as a link to the library `libpoppler.so.86.0.0`. I have tried to create a link to the new library with the old name, but while the program starts, the conversion is messy (wrong size for text and lines).

I could downgrade the `poppler` package, but I was wondering if there was another solution.

**Comment by otfried** [comment]
There was no error message while compiling pdftoipe?

Since you are compiling on your own system, it should link against the library version that you have installed.   I assume you need both  libpoppler and libpoppler-dev packages, perhaps they have different version?

In any case this is an error in compilation - pdftoipe knows nothing about different poppler versions.

**Comment by AA24KK** [comment]
I received no error during the compilation. I also don't have the `libpoppler-dev` library installed, but I received no request for it during the compilation.

I also realized that linking as I mentioned (the new library with the requested name) fixes the problem - the conversion was shoddy because the PDF i tried it on is messy, and on other files it works as intended.

**Comment by otfried** [comment]
What output do you get from `pkg-config --cflags --libs poppler-I/usr/include/poppler -lpoppler`?
