### ISSUE TITLE
Text object of "Page title (Ctrl+p)" converted as wrong size and position by poweripe

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipe-tools#45]
Text object of "Page title (Ctrl+p)" converted as wrong size and position by poweripe.
Text object of "Page title (Ctrl+p)" is not supported by poweripe?

**Comment by otfried** [comment]
Actually Poweripe tries to be smart:  When the page contains a title, then it uses the "titled page" layout in Powerpoint.   So you can move the titles on all pages by just modifying this one layout.

I assume this is what Powerpoint users would really want, so that they can apply Powerpoint styling and layout, isn't it?

**Comment by MasahiroMae** [comment]
I now understand how the page title works.
I changed the slide master and title text becomes good.
Thank you for your advice.
