### ISSUE TITLE
Issue after upgrading to fedora 36 gnome

### ISSUE THREAD

**Issue by manvibharat** [otfried/ipe-tools#51]
If i try to open in fedora 36 gnome

I get the following error:
usr/include/c++/12/bits/stl_vector.h:1122: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = ipe::String; _Alloc = std::allocator<ipe::String>; reference = ipe::String&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)

Is there anything I do to resolve the issue. Any suggestions would be helpful

**Comment by otfried** [comment]
You do not even say which of the ipe-tools you are running.  How do you expect me to help you in any way?

**Comment by manvibharat** [comment]
I am very sorry for that. 
I dont know which tool is causing the problem. But this is what i did. 
I installed ipe in fedora 36 using command
sudo dnf install ipe 
then when i try to run the ipe in terminal by typing "ipe"
I get the error.

I also attach the photo for clarity.
![Problem](https://user-images.githubusercontent.com/25891296/172047800-dfa99453-a221-43dc-a161-303767bf80ed.png)

**Comment by otfried** [comment]
Aha.  If you have a problem with the Ipe program, the issue should go on the Ipe bugtracker (https://github.com/otfried/ipe-issues), not this one here (which is for some separate programs).

It seems Fedora is now compiling with the `-D_GLIBCXX_ASSERTIONS` flag, which breaks some completely harmless statements in Ipe.  

This is already fixed in my sources -  I really need to release a new version.

**Comment by manvibharat** [comment]
O sorry for that mistake. Next time I will make sure I will sure I put in the correct issue tracker. Thanks for the info.
